<h1>Homework 2</h1>
In this notebook there are the activities related to the second homework and, as with the first homework, feel free to use the web to find the solutions to any of these problems. Also, the bonus questions are not mandatory but, if you happen to have the time, try them out too!<br>



<h1>numpy</h1>
Exercise 1: show that now you can import libraries by importing pandas, numpy and matplotlib.

In [20]:
import numpy as np


In [18]:
import matplotlib 
    

In [19]:
import pandas as pd

Exercise 2: Will the following code block work?  

In [21]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array1 = np.random.random((3, 3))
array2 = np.random.random((3, 1))

np.add(array1,array2)

array([[1.09912343, 1.26225187, 0.71290037],
       [1.53984326, 1.87823732, 1.81936783],
       [0.34889484, 0.25363797, 0.74266367]])

Exercise 3: What about now?

In [22]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array3 = np.random.random((3, 3))
array4 = np.random.random((3, 2))

array3.dot(array4)

array([[0.61921096, 1.00685086],
       [1.03139271, 1.27047881],
       [1.05173128, 1.52223866]])

Exercise 4: by inspecting the arrays 1 to 4 can you figure out why one operation worked and another one didn't? (hint: check their values and shape)

In [ ]:
#There shape is not equal (3,1) is not equal to (3,2)

Exercise 5: Using the function to create an array of random numbers [np.random.random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html) how can you modify the code (as in the cells above) so that the numbers will vary between 0 and 100 instead of 0 and 1? And how can you modify the shape of the function?

In [23]:
array3 = np.random.randint(10,size=(3, 3))
array4 = np.random.randint(10,size=(3, 2))

array3.dot(array4)

array([[ 13,  17],
       [ 90, 110],
       [ 24,  34]])

In [24]:
array1 = np.random.randint(65,size=(3, 3))
array2 = np.random.randint(65,size=(3, 1))

np.add(array1,array2)


array([[ 84,  55, 103],
       [ 55,  82,  87],
       [ 60,  69,  75]])

Exercise 6: Using the array defined on the exercise above, use [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) to find the positions the values that are larger than 50 (or feel free to pick any other number).

In [25]:
arr=np.array([[ 26,  57,  19],
       [ 84, 105, 103],
       [ 55, 105, 104]])
np.where((arr>50))

(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 0, 1, 2, 0, 1, 2], dtype=int64))

<h1>Pandas </h1>
There are two datasets on available to this work one is the pokemon dataset we explored in the lectured and the other one is the same dataframe but, for the sake of a nice story, let us say it was sabotaged by team rocket.

Exercise 1: open both dataframes supplied using [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) (and don't forget to assign them to different objects).

In [ ]:
oneDrive_Document_SQL_df = pd.read_csv('Pokemon_csv') 

In [34]:
oneDrive_Document_SQL_df

#                   Name   Type 1  Type 2  Total    HP  Attack  \
0      1              Bulbasaur    Grass  Poison    318  45.0      49   
1      2                Ivysaur    Grass  Poison    405  60.0      62   
2      3               Venusaur    Grass  Poison    525  80.0      82   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80.0     100   
4      4             Charmander     Fire     NaN    309  39.0      52   
..   ...                    ...      ...     ...    ...   ...     ...   
795  719                Diancie     Rock   Fairy    600  50.0     100   
796  719    DiancieMega Diancie     Rock   Fairy    700  50.0     160   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80.0     110   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80.0     160   
799  721              Volcanion     Fire   Water    600  80.0     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       49.0       65     65.0   45.0           1      False  
1       63.0       80     80.0   60.0           1      False  
2       83.0      100    100.0   80.0           1      False  
3      123.0      122    120.0   80.0           1      False  
4       43.0       60     50.0   65.0           1      False  
..       ...      ...      ...    ...         ...        ...  
795    150.0      100    150.0   50.0           6       True  
796    110.0      160    110.0  110.0           6       True  
797     60.0      150    130.0   70.0           6       True  
798     60.0      170    130.0   80.0           6       True  
799    120.0      130     90.0   70.0           6       True  

[800 rows x 13 columns]

Exercise 2: Using [pd.isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) check how many missing numbers are in each dataframe.

In [36]:
df.isna()

#   Name  Type 1  Type 2  Total     HP  Attack  Defense  Sp. Atk  \
0    False  False   False   False  False  False   False    False    False   
1    False  False   False   False  False  False   False    False    False   
2    False  False   False   False  False  False   False    False    False   
3    False  False   False   False  False  False   False    False    False   
4    False  False   False    True  False  False   False    False    False   
..     ...    ...     ...     ...    ...    ...     ...      ...      ...   
795  False  False   False   False  False  False   False    False    False   
796  False  False   False   False  False  False   False    False    False   
797  False  False   False   False  False  False   False    False    False   
798  False  False   False   False  False  False   False    False    False   
799  False  False   False   False  False  False   False    False    False   

     Sp. Def  Speed  Generation  Legendary  
0      False  False       False      False  
1      False  False       False      False  
2      False  False       False      False  
3      False  False       False      False  
4      False  False       False      False  
..       ...    ...         ...        ...  
795    False  False       False      False  
796    False  False       False      False  
797    False  False       False      False  
798    False  False       False      False  
799    False  False       False      False  

[800 rows x 13 columns]

In [37]:
df.isna().sum()

#               0
Name            2
Type 1          1
Type 2        387
Total           0
HP              3
Attack          0
Defense         1
Sp. Atk         0
Sp. Def         1
Speed           4
Generation      0
Legendary       0
dtype: int64

Exercise 3: Two of the main ways to deal with missing data is [pd.dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) and [pd.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html). How are these methods different from each other in how they deal with the missing data? Which, if any, would you use on the dataset? Why?

From now on we will only be working with the main (non sabotaged dataframe).<br>

Exercise 4: to free up memory delete the sabotaged dataframe. Bonus: before deleting find a way to check how much space in memory the dataframes occupy. [hint](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python)

In [42]:
import sys

In [47]:
sys.getsizeof(pd)

72

In [48]:
sys.getsizeof(df)

199279

Exercise 5: Create a new column that contains the sum of the Attack, speed and defense stats.

In [50]:
oneDrive_Document_SQL_df[['HP','Attack','Speed']]

HP  Attack  Speed
0    45.0      49   45.0
1    60.0      62   60.0
2    80.0      82   80.0
3    80.0     100   80.0
4    39.0      52   65.0
..    ...     ...    ...
795  50.0     100   50.0
796  50.0     160  110.0
797  80.0     110   70.0
798  80.0     160   80.0
799  80.0     110   70.0

[800 rows x 3 columns]

Exercise 6: Find out the mean value of the attack, speed, defense columns and the new column that was created above.

In [52]:
np.mean(oneDrive_Document_SQL_df['HP'])

69.22961104140526

In [53]:
np.mean(oneDrive_Document_SQL_df['Attack'])

79.00125

In [54]:
np.mean(oneDrive_Document_SQL_df['Speed'])

68.3894472361809

Exercise 7: Find out how many pokemon have above average stats in the attack, speed, defense and the new column. Bonus: Do the pokemon with above average stats have a preffered type?

In [64]:
oneDrive_Document_SQL_df.dtypes

#               int64
Name           object
Type 1         object
Type 2         object
Total           int64
HP            float64
Attack          int64
Defense       float64
Sp. Atk         int64
Sp. Def       float64
Speed         float64
Generation      int64
Legendary        bool
dtype: object

Super bonus: There are many platforms out there that contain different tools to boost your learning. Then for the super bonus create an account on [kaggle](https://www.kaggle.com/) and complete the courses
[intro to programming](https://www.kaggle.com/learn/intro-to-programming) and [intro to python](https://www.kaggle.com/learn/python) courses. All kaggle courses are free of charge and offer a [certificate](https://www.kaggle.com/learn-course-certificates) !